#!/usr/bin/env python3
"""
generate_tasks.py — Automated task list generator for Me-google xrOS.

Usage:
  python3 scripts/generate_tasks.py            # print task list to stdout
  python3 scripts/generate_tasks.py --json     # output JSON
  python3 scripts/generate_tasks.py --write    # regenerate TASKS.md
  python3 scripts/generate_tasks.py --add      # interactively add a task
  python3 scripts/generate_tasks.py --done TASK-XXX  # mark a task complete
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, field, asdict
from datetime import date
from pathlib import Path
from typing import List, Optional

# ---------------------------------------------------------------------------
# Root of the repository (one level above this script)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
TASKS_FILE = REPO_ROOT / "TASKS.md"

# ---------------------------------------------------------------------------
# Task data model
# ---------------------------------------------------------------------------

@dataclass
class Task:
    id: str
    title: str
    role: str           # agent role from AGENTS.md
    priority: str       # critical | high | medium | low
    status: str         # open | in-progress | blocked | done
    depends_on: List[str] = field(default_factory=list)
    notes: str = ""
    auto: bool = False  # True = generated by repo scan, False = static


# ---------------------------------------------------------------------------
# Static task definitions
# These represent the foundational work items for the Me-google project.
# Add new items here as the project grows, then re-run --write.
# ---------------------------------------------------------------------------

STATIC_TASKS: List[Task] = [
    # ── Foundations ──────────────────────────────────────────────────────
    Task(
        id="TASK-001",
        title="Define and document overall system architecture (ADR-001)",
        role="Architect",
        priority="critical",
        status="open",
        notes="Create docs/adr/ADR-001-system-architecture.md covering spatial OS "
              "model, privacy networking layer, cross-platform strategy.",
    ),
    Task(
        id="TASK-002",
        title="Scaffold monorepo directory structure (core/, platform/, services/, docs/)",
        role="DevOps Engineer",
        priority="critical",
        status="open",
        depends_on=["TASK-001"],
        notes="Create the directory layout described in .github/copilot-instructions.md.",
    ),
    Task(
        id="TASK-003",
        title="Set up CI/CD pipeline (GitHub Actions) for lint + test",
        role="DevOps Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-002"],
        notes="Add .github/workflows/ci.yml targeting all platforms.",
    ),
    # ── Core Logic ───────────────────────────────────────────────────────
    Task(
        id="TASK-004",
        title="Design and implement core data models (Spatial Item, User, Session)",
        role="Core Logic Engineer",
        priority="critical",
        status="open",
        depends_on=["TASK-001", "TASK-002"],
        notes="Language-agnostic schemas first; then typed implementations per platform.",
    ),
    Task(
        id="TASK-005",
        title="Implement local favourites storage with at-rest encryption",
        role="Core Logic Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-004"],
        notes="Privacy checklist required. Use platform keychain/keystore APIs.",
    ),
    Task(
        id="TASK-006",
        title="Write unit tests for core data models",
        role="Core Logic Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-004"],
    ),
    # ── Privacy / Networking ─────────────────────────────────────────────
    Task(
        id="TASK-007",
        title="Research and document anonymous networking approach (Tor / I2P / custom)",
        role="Privacy/Networking Engineer",
        priority="critical",
        status="open",
        depends_on=["TASK-001"],
        notes="Output: docs/adr/ADR-002-privacy-networking.md",
    ),
    Task(
        id="TASK-008",
        title="Implement anonymous identity layer (no PII in network layer)",
        role="Privacy/Networking Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-007"],
    ),
    Task(
        id="TASK-009",
        title="Design real-time sync protocol for spatial item sharing",
        role="Privacy/Networking Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-007", "TASK-004"],
        notes="Consider CRDTs for conflict-free sharing.",
    ),
    # ── iOS / xrOS Platform ──────────────────────────────────────────────
    Task(
        id="TASK-010",
        title="Scaffold iOS/visionOS Xcode project in platform/ios/",
        role="iOS/xrOS Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-002"],
    ),
    Task(
        id="TASK-011",
        title="Implement spatial UI shell (RealityKit window / volume)",
        role="iOS/xrOS Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-010", "TASK-004"],
        notes="Users must be able to place at least one spatial item in AR space.",
    ),
    Task(
        id="TASK-012",
        title="Integrate core data layer into iOS app",
        role="iOS/xrOS Engineer",
        priority="medium",
        status="open",
        depends_on=["TASK-005", "TASK-010"],
    ),
    # ── Android / AR Platform ────────────────────────────────────────────
    Task(
        id="TASK-013",
        title="Scaffold Android project in platform/android/ (Kotlin, Compose, ARCore)",
        role="Android/AR Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-002"],
    ),
    Task(
        id="TASK-014",
        title="Implement spatial UI shell (ARCore anchor + Compose overlay)",
        role="Android/AR Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-013", "TASK-004"],
    ),
    Task(
        id="TASK-015",
        title="Integrate core data layer into Android app",
        role="Android/AR Engineer",
        priority="medium",
        status="open",
        depends_on=["TASK-005", "TASK-013"],
    ),
    # ── Web / WebXR Platform ─────────────────────────────────────────────
    Task(
        id="TASK-016",
        title="Scaffold TypeScript/React WebXR project in platform/web/",
        role="Web/WebXR Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-002"],
    ),
    Task(
        id="TASK-017",
        title="Implement spatial UI shell using WebXR Device API + Three.js / Babylon.js",
        role="Web/WebXR Engineer",
        priority="high",
        status="open",
        depends_on=["TASK-016", "TASK-004"],
    ),
    Task(
        id="TASK-018",
        title="Integrate core data layer into web app",
        role="Web/WebXR Engineer",
        priority="medium",
        status="open",
        depends_on=["TASK-005", "TASK-016"],
    ),
    # ── Documentation ────────────────────────────────────────────────────
    Task(
        id="TASK-019",
        title="Expand README with setup instructions and project roadmap",
        role="Documentation Writer",
        priority="medium",
        status="open",
        depends_on=["TASK-001"],
    ),
    Task(
        id="TASK-020",
        title="Write CONTRIBUTING.md with code style guide and PR process",
        role="Documentation Writer",
        priority="medium",
        status="open",
        depends_on=["TASK-002"],
    ),
]

# Priority sort order
_PRIORITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}


# ---------------------------------------------------------------------------
# Repository scanner — auto-generates tasks from actual repo state
# ---------------------------------------------------------------------------

def scan_repo(tasks: List[Task]) -> List[Task]:
    """Inspect the repository and add auto-generated tasks for obvious gaps."""
    auto_tasks: List[Task] = []
    existing_titles = {t.title.lower() for t in tasks}

    # Check for missing top-level docs
    expected_docs = {
        "docs/adr": ("TASK-A001", "Create docs/adr/ directory for Architecture Decision Records",
                     "Architect", "high"),
        "docs/api": ("TASK-A002", "Create docs/api/ directory for API references",
                     "Documentation Writer", "medium"),
    }
    for rel_path, (tid, title, role, priority) in expected_docs.items():
        if not (REPO_ROOT / rel_path).exists() and title.lower() not in existing_titles:
            auto_tasks.append(Task(
                id=tid, title=title, role=role, priority=priority,
                status="open", auto=True,
                notes=f"Auto-detected: {rel_path} does not exist.",
            ))

    # Check for missing platform scaffolding
    platform_checks = {
        "platform/ios": ("TASK-A010", "Scaffold platform/ios/ directory", "iOS/xrOS Engineer", "high"),
        "platform/android": ("TASK-A013", "Scaffold platform/android/ directory", "Android/AR Engineer", "high"),
        "platform/web": ("TASK-A016", "Scaffold platform/web/ directory", "Web/WebXR Engineer", "high"),
        "core": ("TASK-A004", "Scaffold core/ directory for shared logic", "Core Logic Engineer", "critical"),
        "services": ("TASK-A008", "Scaffold services/ directory for backend micro-services",
                     "Privacy/Networking Engineer", "high"),
    }
    for rel_path, (tid, title, role, priority) in platform_checks.items():
        if not (REPO_ROOT / rel_path).exists() and title.lower() not in existing_titles:
            auto_tasks.append(Task(
                id=tid, title=title, role=role, priority=priority,
                status="open", auto=True,
                notes=f"Auto-detected: {rel_path} does not exist.",
            ))

    # Check for source files missing a corresponding test
    src_dirs = ["core", "services"]
    for src_dir in src_dirs:
        src_path = REPO_ROOT / src_dir
        if not src_path.exists():
            continue
        for src_file in src_path.rglob("*.py"):
            if "test" in src_file.name:
                continue
            test_candidate = src_file.parent / f"test_{src_file.name}"
            if not test_candidate.exists():
                title = f"Add tests for {src_file.relative_to(REPO_ROOT)}"
                if title.lower() not in existing_titles:
                    auto_tasks.append(Task(
                        id=f"TASK-T{len(auto_tasks)+1:03d}",
                        title=title,
                        role="Core Logic Engineer",
                        priority="medium",
                        status="open",
                        auto=True,
                        notes="Auto-detected: no test file found.",
                    ))

    return auto_tasks


# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------

_STATUS_ICON = {
    "open": "⬜",
    "in-progress": "🔄",
    "blocked": "🔴",
    "done": "✅",
}

def _dep_status(dep_id: str, all_tasks: List[Task]) -> str:
    for t in all_tasks:
        if t.id == dep_id:
            return t.status
    return "unknown"


def render_table(tasks: List[Task]) -> str:
    lines: List[str] = []
    lines.append(
        f"| ID | Priority | Status | Role | Title | Depends On |"
    )
    lines.append("|---|---|---|---|---|---|")
    for t in tasks:
        icon = _STATUS_ICON.get(t.status, "❓")
        deps = ", ".join(t.depends_on) if t.depends_on else "—"
        lines.append(
            f"| {t.id} | {t.priority} | {icon} {t.status} | {t.role} | {t.title} | {deps} |"
        )
    return "\n".join(lines)


def render_markdown(all_tasks: List[Task]) -> str:
    today = date.today().isoformat()
    static = [t for t in all_tasks if not t.auto]
    auto   = [t for t in all_tasks if t.auto]

    open_tasks       = [t for t in static if t.status != "done"]
    done_tasks       = [t for t in static if t.status == "done"]
    open_auto        = [t for t in auto   if t.status != "done"]

    lines: List[str] = [
        f"# Me-google — Task List",
        f"",
        f"> Auto-generated on {today} by `scripts/generate_tasks.py`.",
        f"> Do not edit this file by hand — run `python3 scripts/generate_tasks.py --write`.",
        f"",
        f"## Quick Stats",
        f"",
        f"- **Total tasks**: {len(static)}",
        f"- **Open**: {len(open_tasks)}",
        f"- **Done**: {len(done_tasks)}",
        f"- **Auto-detected gaps**: {len(open_auto)}",
        f"",
        f"---",
        f"",
        f"## Open Tasks",
        f"",
        render_table(open_tasks),
        f"",
    ]

    if open_auto:
        lines += [
            f"## Auto-Detected Gaps",
            f"",
            f"These tasks were generated by scanning the repository for missing structure.",
            f"",
            render_table(open_auto),
            f"",
        ]

    if done_tasks:
        lines += [
            f"## Completed Tasks",
            f"",
            render_table(done_tasks),
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"## Notes",
        f"",
        f"- Pick a task whose dependencies all show ✅ done.",
        f"- Open a PR titled `[TASK-XXX] Short description`.",
        f"- Run `python3 scripts/generate_tasks.py --done TASK-XXX --write` after merging.",
        f"- See `AGENTS.md` for role definitions and workflow.",
        f"",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# State persistence (simple JSON sidecar next to TASKS.md)
# ---------------------------------------------------------------------------

STATE_FILE = REPO_ROOT / ".task-state.json"


def load_state() -> dict:
    if STATE_FILE.exists():
        with STATE_FILE.open() as f:
            return json.load(f)
    return {}


def save_state(state: dict) -> None:
    with STATE_FILE.open("w") as f:
        json.dump(state, f, indent=2)
    print(f"State saved to {STATE_FILE.relative_to(REPO_ROOT)}")


def apply_state(tasks: List[Task], state: dict) -> None:
    """Overlay persisted status changes onto the task list."""
    overrides = state.get("status_overrides", {})
    for task in tasks:
        if task.id in overrides:
            task.status = overrides[task.id]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_task_list() -> List[Task]:
    tasks = list(STATIC_TASKS)
    auto = scan_repo(tasks)
    tasks.extend(auto)
    state = load_state()
    apply_state(tasks, state)
    tasks.sort(key=lambda t: (_PRIORITY_ORDER.get(t.priority, 9), t.id))
    return tasks


def cmd_list(args: argparse.Namespace) -> None:
    tasks = build_task_list()
    if args.json:
        print(json.dumps([asdict(t) for t in tasks], indent=2))
    else:
        print(render_markdown(tasks))


def cmd_write(args: argparse.Namespace) -> None:
    tasks = build_task_list()
    content = render_markdown(tasks)
    TASKS_FILE.write_text(content)
    print(f"Written: {TASKS_FILE.relative_to(REPO_ROOT)}")


def cmd_done(args: argparse.Namespace) -> None:
    task_id: str = args.done.upper()
    state = load_state()
    overrides = state.setdefault("status_overrides", {})
    overrides[task_id] = "done"
    save_state(state)
    print(f"{task_id} marked as done.")
    if getattr(args, "write", False):
        cmd_write(args)


def cmd_add(args: argparse.Namespace) -> None:
    """Interactively add a custom task to the state file."""
    print("Add a new task (press Ctrl-C to cancel):")
    try:
        tid   = input("  Task ID (e.g. TASK-021): ").strip()
        title = input("  Title: ").strip()
        role  = input("  Role: ").strip()
        prio  = input("  Priority [critical/high/medium/low]: ").strip() or "medium"
        deps  = input("  Depends on (comma-separated IDs, or blank): ").strip()
        notes = input("  Notes (optional): ").strip()
    except KeyboardInterrupt:
        print("\nAborted.")
        return

    state = load_state()
    custom = state.setdefault("custom_tasks", [])
    custom.append({
        "id": tid, "title": title, "role": role, "priority": prio,
        "status": "open",
        "depends_on": [d.strip() for d in deps.split(",") if d.strip()],
        "notes": notes, "auto": False,
    })
    save_state(state)
    print(f"Task {tid} added.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Me-google automated task list generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--json",  action="store_true", help="Output as JSON")
    parser.add_argument("--write", action="store_true", help="Write TASKS.md")
    parser.add_argument("--add",   action="store_true", help="Add a task interactively")
    parser.add_argument("--done",  metavar="TASK-ID",   help="Mark a task done")

    args = parser.parse_args()

    if args.done:
        cmd_done(args)
        if args.write:
            cmd_write(args)
    elif args.add:
        cmd_add(args)
        if args.write:
            cmd_write(args)
    elif args.write:
        cmd_write(args)
    else:
        cmd_list(args)


if __name__ == "__main__":
    main()
