#!/usr/bin/env python3
"""Pre-mortem — the forward loop (ADR-009, Loop 3).

Writes scenario fiction to reports/premortem-YYYY-MM-DD.md: concrete
narratives of plausible failure futures across the four standing threat
quadrants, each ending with the earliest observable warning sign.
Read-and-report only.

Usage:
  python3 scripts/premortem.py            # write the report
  python3 scripts/premortem.py --dry-run  # print the prompt, call nothing
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import ai_client
from scout import open_tasks_snapshot

REPO_ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = REPO_ROOT / "reports"
ADR_DIR = REPO_ROOT / "docs" / "adr"

QUADRANTS = [
    (
        "The autonomy machinery itself",
        "gate-gaming, baseline corruption, a buggy blocking gate freezing the loop, "
        "self-modification paths around the ADR-008 firewall, a poisoned scout digest "
        "steering a later coding session",
    ),
    (
        "The privacy architecture",
        "correlation attacks, metadata leakage, key compromise in the anonymous "
        "identity and encrypted sync designs (ADR-002, core/models/session.ts)",
    ),
    (
        "Product & UX failure modes",
        "anchor drift, lost placements, sync conflicts where two users both 'win', "
        "constraints that should shape TASK-005/TASK-009 before code exists",
    ),
    (
        "Project-level risks",
        "single maintainer, hardware dependency, platform rug-pulls, API token cost "
        "drift, a scheduled loop dying silently",
    ),
]

SYSTEM_PROMPT = """\
You are the Red Team / Pre-mortem Author for Me-google, a privacy-first \
spatial-computing sandbox developed largely by AI agents. You write scenario \
fiction: short, concrete narratives of plausible failure futures, each told \
as if the failure already happened. This imaginative register is deliberate — \
it surfaces failure shapes that a likelihood-times-impact spreadsheet \
flattens.

Rules (from ADR-009): 4-8 scenarios total, covering all four quadrants, the \
autonomy machinery first. Each scenario: a title, a dated narrative of how it \
unfolded (grounded in the repo's real files, ADRs, and tasks — name them), \
then two closing lines: 'Earliest warning sign:' (something observable in the \
repo, CI, or reports) and 'Cheapest prevention:' (the smallest change that \
would have broken the causal chain). You report only — a human decides what \
hardens into a task, gate, or ADR amendment. Output clean Markdown."""


def adr_snapshot() -> str:
    if not ADR_DIR.exists():
        return "(no ADRs found)"
    titles = []
    for adr in sorted(ADR_DIR.glob("ADR-*.md")):
        first = adr.read_text(errors="replace").splitlines()
        titles.append(first[0].lstrip("# ").strip() if first else adr.name)
    return "\n".join(f"- {t}" for t in titles)


def build_user_prompt(today: str) -> str:
    quadrants = "\n".join(f"- **{name}** — {scope}." for name, scope in QUADRANTS)
    return f"""Today is {today}. Write this month's pre-mortem.

Standing threat quadrants:
{quadrants}

Architecture decisions in force:
{adr_snapshot()}

Open tasks (cite IDs where relevant):
{open_tasks_snapshot()}

Write the scenarios now."""


def render_report(body: str, today: str) -> str:
    header = (
        f"# Pre-mortem — {today}\n\n"
        f"> Generated by `scripts/premortem.py` (model: {ai_client.model()}) per ADR-009.\n"
        f"> Scenario fiction, not prediction. Promote credible scenarios by hand into "
        f"tasks, gates, or ADR amendments.\n\n"
    )
    return header + body.strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Me-google pre-mortem author (ADR-009).")
    parser.add_argument("--dry-run", action="store_true", help="print prompt and exit")
    args = parser.parse_args()

    today = dt.date.today().isoformat()
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": build_user_prompt(today)},
    ]

    if args.dry_run:
        print(messages[0]["content"])
        print("\n---\n")
        print(messages[1]["content"])
        return 0

    if not ai_client.have_key():
        print("AI_API_KEY not set — skipping pre-mortem run (no report written).")
        return 0

    body = ai_client.chat(messages, live_search=False, max_tokens=6000, temperature=0.7)
    REPORTS_DIR.mkdir(exist_ok=True)
    out = REPORTS_DIR / f"premortem-{today}.md"
    out.write_text(render_report(body, today))
    print(f"Wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
